"""Canonical deck identities, batches, and private registry contracts."""

from ptcg_rl.decks.batch import (
    DeckBatch,
    concatenate_deck_batches,
    copy_deck_batch_,
    empty_deck_batch_like,
    pad_deck_batch,
)
from ptcg_rl.decks.identity import (
    DECK_SIZE,
    CanonicalDeck,
    canonical_signature,
    canonicalize_deck,
    deck_digest,
    deck_module_key,
    parse_canonical_signature,
)
from ptcg_rl.decks.registry import (
    DeckExpertRoute,
    DeckFamilyRoute,
    PrivateDeckProfile,
    PrivateDeckRegistrySourceConfig,
    PrivateDeckSourceConfig,
    ResolvedDeckExpertRegistry,
    ResolvedDeckFamilyRegistry,
    ResolvedPrivateDeckRegistry,
    deck_expert_registry_fingerprint,
    deck_expert_route,
    deck_family_registry_fingerprint,
    deck_family_route,
    private_deck_profile,
    private_registry_fingerprint,
    resolve_deck_expert_registry,
    resolve_deck_family_registry,
    resolve_private_registry,
    validate_active_exact_strategy_routes,
)

__all__ = [
    "DECK_SIZE",
    "CanonicalDeck",
    "DeckBatch",
    "DeckExpertRoute",
    "DeckFamilyRoute",
    "PrivateDeckProfile",
    "PrivateDeckRegistrySourceConfig",
    "PrivateDeckSourceConfig",
    "ResolvedDeckExpertRegistry",
    "ResolvedDeckFamilyRegistry",
    "ResolvedPrivateDeckRegistry",
    "canonical_signature",
    "canonicalize_deck",
    "concatenate_deck_batches",
    "copy_deck_batch_",
    "deck_digest",
    "deck_expert_registry_fingerprint",
    "deck_expert_route",
    "deck_family_registry_fingerprint",
    "deck_family_route",
    "deck_module_key",
    "empty_deck_batch_like",
    "parse_canonical_signature",
    "pad_deck_batch",
    "private_deck_profile",
    "private_registry_fingerprint",
    "resolve_deck_expert_registry",
    "resolve_deck_family_registry",
    "resolve_private_registry",
    "validate_active_exact_strategy_routes",
]
