"""Clean stateless policy architecture for the new RL lineage."""

from ptcg_rl.model.simple_stateless.backbone import (
    CountAwareDeckEncoder,
    SimpleStatelessBackbone,
    SimpleStatelessBackboneOutput,
    SimpleStatelessInputEncoder,
    select_simple_stateless_backbone_rows,
)
from ptcg_rl.model.simple_stateless.belief import (
    OpponentCardBeliefHead,
    PublicBeliefSummaryBatch,
    PublicBeliefSummaryEncoder,
    SparseBeliefTargets,
    build_sparse_belief_targets,
    collate_public_belief_summaries,
    normalized_sparse_belief_loss,
    normalized_sparse_belief_row_losses,
)
from ptcg_rl.model.simple_stateless.config import (
    SIMPLE_BELIEF_TARGET_SEMANTICS,
    SIMPLE_STATELESS_ARCHITECTURE,
    SIMPLE_STATELESS_V2_ARCHITECTURE,
    PolicyModelConfig,
    SimpleStatelessModelConfig,
    model_architecture_name,
    parse_policy_model_config,
    uses_exact_v2_topology,
    uses_family_private_topology,
    uses_generalist_sequence,
    uses_temporal_prefusion,
    uses_wdl_critic,
)
from ptcg_rl.model.simple_stateless.family_private import (
    FAMILY_PRIVATE_ACTIVE_LAYERS,
    FAMILY_PRIVATE_APPENDED_LAYERS,
    FAMILY_PRIVATE_CLONED_LAYERS,
    FAMILY_PRIVATE_INHERITED_LAYERS,
    FAMILY_PRIVATE_SHARED_LAYERS,
    FamilyPrivateStrategyBank,
    FamilyPrivateTransformerTail,
)
from ptcg_rl.model.simple_stateless.heads import (
    ExactOptionEmbeddingResidual,
    ExactPolicyQueryResidual,
    ExactScalarValueResidual,
    SimpleGreedyDecodeTrace,
    SimplePolicyStep,
    SimpleSampledDecodeTrace,
    SimpleStatelessPolicyValueHeads,
    SimpleTeacherForcedActionBatch,
    SimpleTeacherForcedActionInput,
    SimpleTeacherForcedEvaluation,
    simple_count_first_rows,
)
from ptcg_rl.model.simple_stateless.layers import (
    PackedLearnerInductorError,
    PackedRolloutInductorError,
    PackedSelfAttention,
    PackedTransformerBlock,
    PackedTransformerTrunk,
    initialize_simple_stateless_module,
)
from ptcg_rl.model.simple_stateless.network import (
    SimpleStatelessPolicyValueNet,
    materialize_simple_stateless_checkpoint_model,
)
from ptcg_rl.model.simple_stateless.options import RoleAwareOptionEncoder
from ptcg_rl.model.simple_stateless.packed import (
    PackedTokenBatch,
    SpecialTokenPositions,
    prepend_special_tokens,
    unpack_after_prefix,
)
from ptcg_rl.model.simple_stateless.reporting import (
    simple_stateless_parameter_report,
    validate_simple_stateless_parameter_report,
)
from ptcg_rl.model.simple_stateless.routing import (
    SimpleExactRoutePlan,
    resolve_simple_exact_routes,
    resolve_simple_pretraining_routes,
)
from ptcg_rl.model.simple_stateless.state import SimpleStatelessRawStateEncoder
from ptcg_rl.model.simple_stateless.temporal_fusion import (
    GatedTemporalContentFusion,
)
from ptcg_rl.model.simple_stateless.v2 import (
    GENERALIST_SEQUENCE_V2_CAPSULE_STAGES,
    SIMPLE_STATELESS_V2_BASIS_RANK,
    SIMPLE_STATELESS_V2_CAPSULE_STAGES,
    SIMPLE_STATELESS_V2_EXACT_BOTTLENECK,
    SIMPLE_STATELESS_V2_SHARED_BASES,
    CompositionalCapsuleStage,
    ExactCompositionalCapsule,
    ExactSemanticPrompt,
    SimpleStatelessV2Adapters,
    ZeroOutputBottleneckResidual,
    gather_semantic_tokens,
    replace_semantic_tokens,
)
from ptcg_rl.model.simple_stateless.value import (
    DistributionalWdlCritic,
    ExactWdlValueResidual,
    two_hot_wdl_targets,
    wdl_value_from_logits,
)

__all__ = [
    "CountAwareDeckEncoder",
    "CompositionalCapsuleStage",
    "ExactCompositionalCapsule",
    "ExactOptionEmbeddingResidual",
    "ExactPolicyQueryResidual",
    "ExactScalarValueResidual",
    "ExactSemanticPrompt",
    "ExactWdlValueResidual",
    "DistributionalWdlCritic",
    "FAMILY_PRIVATE_ACTIVE_LAYERS",
    "FAMILY_PRIVATE_APPENDED_LAYERS",
    "FAMILY_PRIVATE_CLONED_LAYERS",
    "FAMILY_PRIVATE_INHERITED_LAYERS",
    "FAMILY_PRIVATE_SHARED_LAYERS",
    "FamilyPrivateStrategyBank",
    "FamilyPrivateTransformerTail",
    "GENERALIST_SEQUENCE_V2_CAPSULE_STAGES",
    "GatedTemporalContentFusion",
    "OpponentCardBeliefHead",
    "PackedLearnerInductorError",
    "PackedRolloutInductorError",
    "PackedSelfAttention",
    "PackedTokenBatch",
    "PackedTransformerBlock",
    "PackedTransformerTrunk",
    "SIMPLE_STATELESS_ARCHITECTURE",
    "SIMPLE_STATELESS_V2_ARCHITECTURE",
    "SIMPLE_STATELESS_V2_BASIS_RANK",
    "SIMPLE_STATELESS_V2_CAPSULE_STAGES",
    "SIMPLE_STATELESS_V2_EXACT_BOTTLENECK",
    "SIMPLE_STATELESS_V2_SHARED_BASES",
    "SIMPLE_BELIEF_TARGET_SEMANTICS",
    "PolicyModelConfig",
    "PublicBeliefSummaryBatch",
    "PublicBeliefSummaryEncoder",
    "RoleAwareOptionEncoder",
    "SimpleGreedyDecodeTrace",
    "SimpleExactRoutePlan",
    "SimplePolicyStep",
    "SimpleSampledDecodeTrace",
    "SimpleStatelessBackbone",
    "SimpleStatelessBackboneOutput",
    "SimpleStatelessInputEncoder",
    "SimpleStatelessModelConfig",
    "SimpleStatelessPolicyValueHeads",
    "SimpleStatelessPolicyValueNet",
    "SimpleStatelessRawStateEncoder",
    "SimpleStatelessV2Adapters",
    "SimpleTeacherForcedActionBatch",
    "SimpleTeacherForcedActionInput",
    "SimpleTeacherForcedEvaluation",
    "SparseBeliefTargets",
    "SpecialTokenPositions",
    "build_sparse_belief_targets",
    "collate_public_belief_summaries",
    "initialize_simple_stateless_module",
    "materialize_simple_stateless_checkpoint_model",
    "gather_semantic_tokens",
    "model_architecture_name",
    "normalized_sparse_belief_loss",
    "normalized_sparse_belief_row_losses",
    "parse_policy_model_config",
    "prepend_special_tokens",
    "replace_semantic_tokens",
    "resolve_simple_exact_routes",
    "resolve_simple_pretraining_routes",
    "simple_stateless_parameter_report",
    "select_simple_stateless_backbone_rows",
    "simple_count_first_rows",
    "unpack_after_prefix",
    "uses_exact_v2_topology",
    "uses_family_private_topology",
    "uses_generalist_sequence",
    "uses_temporal_prefusion",
    "uses_wdl_critic",
    "validate_simple_stateless_parameter_report",
    "two_hot_wdl_targets",
    "wdl_value_from_logits",
    "ZeroOutputBottleneckResidual",
]
